#! /usr/bin/bash
#echo "Hello World How are you today"

#a=Hello
#b=Good
#echo $a $b

#a=2;
#B=4;
#sum=$((2+4));
#echo $sum

#echo "Enter first number"
#read a
#echo "Enter second number"
#read b
#sum=$((a+b))
#echo "The sum of the two nuumber is $sum"
#sub=$((a-b))
#echo "The Substitution of two number is $sub"
#div=$((a / b))
#echo "The divison of two number is $div"
#mul=$((a * b))
#echo "The multiple of two number is $mul"

#echo "Enter the first digit as a x"
#read x
#echo "Enter the second digit as y"
#read y
#if [ $x -gt $y ]
#then
#echo "$x is greater than the $y"
#elif [ $x -lt $y ]
#then
#echo "$x is less then the $y"
#elif [ $x -eq $y ]
#then
#echo "The $x is equal to $y"
#fi

#echo "Enter the age of the candidate for election:"
#read age
#if [[ $age -gt 18 ]]
#then
#    echo "The voter is eligible to vote"
#elif [[ $age -lt 18 ]]
#then
#    echo "The voter is not eligible as age criteria is not met"
#elif [[ $age -eq 18 ]]
#then
 #   echo "WELCOME, you are giving the first vote!"
#fi

#for i in {1..10}
#do
#	echo $i
#done


#for x in { nagaraj khairate }
#do
#	echo $x
#done


